--liquibase formatted sql
--changeset bruno.lima:1
CREATE TABLE PEDIDOS_ITENS (
    ID              BIGINT PRIMARY KEY,
    I_PRODUTOS      BIGINT,
    I_PEDIDOS       BIGINT,
    QUANTIDADE      INT,
    FL_EXCLUIDO     BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_PEDIDOS_ITENS_PRODUTOS FOREIGN KEY (I_PRODUTOS) REFERENCES PRODUTOS(id),
    CONSTRAINT FK_PEDIDOS_ITENS_PEDIDOS FOREIGN KEY (I_PEDIDOS) REFERENCES PEDIDOS(id)
);
--rollback not required

--changeset bruno.lima:2
CREATE SEQUENCE SEQ_PEDIDOS_ITENS START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
--rollback not required